#!/bin/bash
#
# frontmatter-to-schema wrapper script
# Replaces compiled binary with deno run execution
#

exec deno run --allow-read --allow-write --allow-env --allow-run "$(dirname "$0")/src/cli.ts" "$@"