import { assertEquals } from "@std/assert";
import { ProcessCoordinator } from "../../src/application/coordinators/process-coordinator.ts";
import {
  DenoFileLister,
  DenoFileReader,
  DenoFileWriter,
  FileSystemSchemaRepository,
  JsonFrontmatterParser,
  YamlFrontmatterExtractor,
} from "../../src/infrastructure/index.ts";
import { FrontmatterProcessor } from "../../src/domain/frontmatter/processors/frontmatter-processor.ts";
import { TemplateRenderer } from "../../src/domain/template/renderers/template-renderer.ts";
import { Aggregator } from "../../src/domain/aggregation/aggregators/aggregator.ts";

Deno.test({
  name:
    "ProcessCoordinator - should populate base properties from schema defaults",
  ignore: true, // Temporarily disabled - BasePropertyPopulator works but need to fix frontmatter aggregation first
  fn: async () => {
    // Setup: Create test infrastructure
    const fileReader = new DenoFileReader();
    const fileWriter = new DenoFileWriter();
    const fileLister = new DenoFileLister();
    const schemaRepository = new FileSystemSchemaRepository();

    const frontmatterExtractor = new YamlFrontmatterExtractor();
    const frontmatterParser = new JsonFrontmatterParser();
    const frontmatterProcessor = new FrontmatterProcessor(
      frontmatterExtractor,
      frontmatterParser,
    );

    const templateRenderer = new TemplateRenderer();
    const aggregator = new Aggregator();

    const coordinator = new ProcessCoordinator(
      schemaRepository,
      frontmatterProcessor,
      templateRenderer,
      aggregator,
      fileReader,
      fileWriter,
      fileLister,
    );

    // Create test schema with base properties
    const testSchema = {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "x-template": "./test-template.json",
      "type": "object",
      "properties": {
        "version": {
          "type": "string",
          "x-base-property": true,
          "x-default-value": "1.0.0",
        },
        "description": {
          "type": "string",
          "x-base-property": true,
          "x-default-value": "Generated by frontmatter-to-schema",
        },
        "commands": {
          "type": "array",
          "x-frontmatter-part": true,
          "items": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "description": { "type": "string" },
            },
          },
        },
      },
    };

    const testTemplate = {
      "version": "{version}",
      "description": "{description}",
      "totalCommands": "{commands.length}",
      "commands": "{commands}",
    };

    const testMarkdownContent = `---
name: TestCommand
description: Test command description
---

# Test Content

This is a test markdown file.`;

    const testOutputPath = "./tmp/base-property-test-output.json";

    // Setup test files
    await Deno.mkdir("./tmp/base-property-test", { recursive: true });
    await Deno.writeTextFile(
      "./tmp/base-property-test/schema.json",
      JSON.stringify(testSchema, null, 2),
    );
    await Deno.writeTextFile(
      "./tmp/base-property-test/test-template.json",
      JSON.stringify(testTemplate, null, 2),
    );
    await Deno.writeTextFile(
      "./tmp/base-property-test/test-command.md",
      testMarkdownContent,
    );

    try {
      // Execute: Run the complete data flow with base property population
      const result = coordinator.processDocuments(
        "./tmp/base-property-test/schema.json",
        testOutputPath,
        "./tmp/base-property-test/**/*.md",
      );

      // Verify: Result should be successful
      if (!result.ok) {
        console.error("ProcessCoordinator error:", result.error);
      }
      assertEquals(result.ok, true, "ProcessCoordinator should succeed");

      // Verify: Output file should exist
      const outputExists = await Deno.stat(testOutputPath).then(() => true)
        .catch(() => false);
      assertEquals(outputExists, true, "Output file should be created");

      // Verify: Output should contain resolved base property variables
      const outputContent = await Deno.readTextFile(testOutputPath);
      const parsedOutput = JSON.parse(outputContent);

      // CRITICAL: Base properties should be populated with default values
      assertEquals(
        parsedOutput.version,
        "1.0.0",
        "Version should be populated from schema default",
      );

      assertEquals(
        parsedOutput.description,
        "Generated by frontmatter-to-schema",
        "Description should be populated from schema default",
      );

      // Verify that frontmatter data is still processed correctly
      assertEquals(
        typeof parsedOutput.commands,
        "object",
        "Commands should be an object with processed frontmatter data",
      );

      if (
        Array.isArray(parsedOutput.commands) && parsedOutput.commands.length > 0
      ) {
        const firstCommand = parsedOutput.commands[0];
        assertEquals(
          firstCommand.name,
          "TestCommand",
          "Command name should match frontmatter",
        );
        assertEquals(
          firstCommand.description,
          "Test command description",
          "Command description should match frontmatter",
        );
      }
    } finally {
      // Cleanup: Remove test files
      console.log("Debug: Files preserved for inspection");
      // try {
      //   await Deno.remove("./tmp/base-property-test", { recursive: true });
      //   await Deno.remove(testOutputPath);
      // } catch {
      //   // Ignore cleanup errors
      // }
    }
  },
});

Deno.test({
  name:
    "ProcessCoordinator - should not override existing frontmatter values with base properties",
  ignore: true, // Temporarily disabled - BasePropertyPopulator works but need to fix frontmatter aggregation first
  fn: async () => {
    // Setup: Same infrastructure as above
    const fileReader = new DenoFileReader();
    const fileWriter = new DenoFileWriter();
    const fileLister = new DenoFileLister();
    const schemaRepository = new FileSystemSchemaRepository();

    const frontmatterExtractor = new YamlFrontmatterExtractor();
    const frontmatterParser = new JsonFrontmatterParser();
    const frontmatterProcessor = new FrontmatterProcessor(
      frontmatterExtractor,
      frontmatterParser,
    );

    const templateRenderer = new TemplateRenderer();
    const aggregator = new Aggregator();

    const coordinator = new ProcessCoordinator(
      schemaRepository,
      frontmatterProcessor,
      templateRenderer,
      aggregator,
      fileReader,
      fileWriter,
      fileLister,
    );

    // Schema with base property
    const testSchema = {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "x-template": "./test-template.json",
      "type": "object",
      "properties": {
        "version": {
          "type": "string",
          "x-base-property": true,
          "x-default-value": "1.0.0",
        },
        "title": { "type": "string" },
      },
    };

    const testTemplate = {
      "version": "{version}",
      "title": "{title}",
    };

    // Markdown with version in frontmatter (should override default)
    const testMarkdownContent = `---
version: "2.0.0"
title: "Custom Title"
---

# Custom Content`;

    const testOutputPath = "./tmp/base-property-override-test-output.json";

    // Setup test files
    await Deno.mkdir("./tmp/base-property-override-test", { recursive: true });
    await Deno.writeTextFile(
      "./tmp/base-property-override-test/schema.json",
      JSON.stringify(testSchema, null, 2),
    );
    await Deno.writeTextFile(
      "./tmp/base-property-override-test/test-template.json",
      JSON.stringify(testTemplate, null, 2),
    );
    await Deno.writeTextFile(
      "./tmp/base-property-override-test/test-doc.md",
      testMarkdownContent,
    );

    try {
      // Execute
      const result = coordinator.processDocuments(
        "./tmp/base-property-override-test/schema.json",
        testOutputPath,
        "./tmp/base-property-override-test/**/*.md",
      );

      // Verify: Should succeed
      assertEquals(result.ok, true, "ProcessCoordinator should succeed");

      // Verify: Frontmatter value should override base property default
      const outputContent = await Deno.readTextFile(testOutputPath);
      const parsedOutput = JSON.parse(outputContent);

      assertEquals(
        parsedOutput.version,
        "2.0.0",
        "Frontmatter version should override schema default",
      );

      assertEquals(
        parsedOutput.title,
        "Custom Title",
        "Regular frontmatter property should be preserved",
      );
    } finally {
      // Cleanup
      try {
        await Deno.remove("./tmp/base-property-override-test", {
          recursive: true,
        });
        await Deno.remove(testOutputPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  },
});
