import { assertEquals } from "@std/assert";
import { BasePropertyPopulator } from "../../../src/domain/schema/services/base-property-populator.ts";
import { Schema } from "../../../src/domain/schema/entities/schema.ts";
import { SchemaPath } from "../../../src/domain/schema/value-objects/schema-path.ts";
import { SchemaDefinition } from "../../../src/domain/schema/value-objects/schema-definition.ts";
import { FrontmatterData } from "../../../src/domain/frontmatter/value-objects/frontmatter-data.ts";

// Test helper to create schema from data
function createTestSchema(schemaData: any): Schema {
  const pathResult = SchemaPath.create("test.json");
  if (!pathResult.ok) throw new Error("Path creation failed");

  const definitionResult = SchemaDefinition.create(schemaData);
  if (!definitionResult.ok) throw new Error("Definition creation failed");

  const schemaResult = Schema.create(pathResult.data, definitionResult.data);
  if (!schemaResult.ok) throw new Error("Schema creation failed");

  return schemaResult.data;
}

function createTestFrontmatter(data: any): FrontmatterData {
  const result = FrontmatterData.create(data);
  if (!result.ok) throw new Error("Frontmatter creation failed");
  return result.data;
}

Deno.test({
  name:
    "BasePropertyPopulator - should populate version from schema default value",
  fn: () => {
    // Arrange: Create schema with base property default
    const schemaData = {
      properties: {
        version: {
          type: "string",
          "x-base-property": true,
          "x-default-value": "1.0.0",
        },
      },
    };

    const schema = createTestSchema(schemaData);
    const populator = new BasePropertyPopulator();
    const frontmatterData = createTestFrontmatter({});

    // Act: Populate base properties
    const result = populator.populate(frontmatterData, schema);

    // Assert: Version should be populated with default value
    assertEquals(result.ok, true, "Base property population should succeed");
    if (!result.ok) return;

    const populatedData = result.data;
    assertEquals(
      populatedData.get("version"),
      "1.0.0",
      "Version should be populated with default value",
    );
  },
});

Deno.test({
  name:
    "BasePropertyPopulator - should populate description from schema default",
  fn: () => {
    // Arrange
    const schemaData = {
      properties: {
        description: {
          type: "string",
          "x-base-property": true,
          "x-default-value": "Generated by frontmatter-to-schema",
        },
      },
    };

    const schema = createTestSchema(schemaData);
    const populator = new BasePropertyPopulator();
    const frontmatterData = createTestFrontmatter({});

    // Act
    const result = populator.populate(frontmatterData, schema);

    // Assert
    assertEquals(result.ok, true);
    if (!result.ok) return;

    assertEquals(
      result.data.get("description"),
      "Generated by frontmatter-to-schema",
    );
  },
});

Deno.test({
  name:
    "BasePropertyPopulator - should merge base properties with existing frontmatter data",
  fn: () => {
    // Arrange
    const schemaData = {
      properties: {
        version: {
          type: "string",
          "x-base-property": true,
          "x-default-value": "1.0.0",
        },
        title: {
          type: "string", // Non-base property
        },
      },
    };

    const schema = createTestSchema(schemaData);
    const populator = new BasePropertyPopulator();

    // Frontmatter data with existing properties
    const frontmatterData = createTestFrontmatter({
      title: "Existing Title",
      author: "John Doe",
    });

    // Act
    const result = populator.populate(frontmatterData, schema);

    // Assert: Should have both base and existing properties
    assertEquals(result.ok, true);
    if (!result.ok) return;

    const data = result.data;
    assertEquals(data.get("version"), "1.0.0", "Base property should be added");
    assertEquals(
      data.get("title"),
      "Existing Title",
      "Existing property should be preserved",
    );
    assertEquals(
      data.get("author"),
      "John Doe",
      "Non-schema property should be preserved",
    );
  },
});

Deno.test({
  name:
    "BasePropertyPopulator - should not override existing frontmatter values",
  fn: () => {
    // Arrange
    const schemaData = {
      properties: {
        version: {
          type: "string",
          "x-base-property": true,
          "x-default-value": "1.0.0",
        },
      },
    };

    const schema = createTestSchema(schemaData);
    const populator = new BasePropertyPopulator();

    // Frontmatter already has version
    const frontmatterData = createTestFrontmatter({
      version: "2.0.0", // Different from default
    });

    // Act
    const result = populator.populate(frontmatterData, schema);

    // Assert: Existing value should be preserved
    assertEquals(result.ok, true);
    if (!result.ok) return;

    assertEquals(
      result.data.get("version"),
      "2.0.0",
      "Existing frontmatter value should not be overridden",
    );
  },
});

Deno.test({
  name: "BasePropertyPopulator - should handle schema without base properties",
  fn: () => {
    // Arrange
    const schemaData = {
      properties: {
        title: { type: "string" }, // No base properties
        commands: { type: "array" },
      },
    };

    const schema = createTestSchema(schemaData);
    const populator = new BasePropertyPopulator();
    const frontmatterData = createTestFrontmatter({ title: "Test" });

    // Act
    const result = populator.populate(frontmatterData, schema);

    // Assert: Should return unchanged data
    assertEquals(result.ok, true);
    if (!result.ok) return;

    assertEquals(result.data.get("title"), "Test");
  },
});

Deno.test({
  name:
    "BasePropertyPopulator - should return error for invalid base property configuration",
  fn: () => {
    // Arrange: Schema with base property but missing default value
    const schemaData = {
      properties: {
        version: {
          type: "string",
          "x-base-property": true,
          // Missing x-default-value
        },
      },
    };

    const schema = createTestSchema(schemaData);
    const populator = new BasePropertyPopulator();
    const frontmatterData = createTestFrontmatter({});

    // Act
    const result = populator.populate(frontmatterData, schema);

    // Assert: Should return error
    assertEquals(
      result.ok,
      false,
      "Should fail when base property lacks default value",
    );
    if (result.ok) return;

    assertEquals(
      result.error.kind,
      "InvalidSchema",
      "Error should indicate invalid schema",
    );
  },
});
